name: flutter_media_metadata_plus
description: A high-performance Flutter plugin to read metadata and album art of media files.
version: 1.2.7
homepage: https://github.com/PuzzleTakX/flutter_media_metadata_plus
repository: https://github.com/PuzzleTakX/flutter_media_metadata_plus
documentation: https://github.com/PuzzleTakX/flutter_media_metadata_plus/blob/master/README.md

screenshots:
  - description: 'Package Logo'
    path: icon/logo.png

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.puzzletakx.flutter_media_metadata_plus
        pluginClass: FlutterMediaMetadataPlugin
      windows:
        pluginClass: FlutterMediaMetadataPlugin
      linux:
        pluginClass: FlutterMediaMetadataPlugin
      ios:
        pluginClass: FlutterMediaMetadataPlugin
      macos:
        pluginClass: FlutterMediaMetadataPlugin
      web:
        pluginClass: MetadataRetriever
        fileName: src/flutter_media_metadata_web.dart
